language: ruby

notifications:
  email:
    - kill-bill-commits@googlegroups.com

rvm:
  - jruby-19mode
  - jruby-20mode
  - jruby-head

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

matrix:
  allow_failures:
    - rvm: jruby-head
